### ISSUE TITLE
NEW LOGO

### ISSUE THREAD

**Issue by rijal10** [puffstream/stream-base-product#18]
Hello puffstream.!
You have a great app, unfortunately this app does not have a logo yet, may I donate a logo for your app?

**Comment by jamesstar89** [comment]
Sure, lets see what ya got :)

**Comment by rijal10** [comment]
May I know what kind of logo @puffstream wants?

**Comment by jamesstar89** [comment]
Hey @rijal10,

I've posted some ideas on Twitter - https://twitter.com/puffstream/status/1014788479769690112

Something that represents: flow, stream, colors

**Comment by rijal10** [comment]
[stream.pdf](https://github.com/puffstream/stream/files/2169550/stream.pdf)

**Comment by rijal10** [comment]
I think the design is more suitable and elegant because the logo includes all of your applications that I learned!
![capture](https://user-images.githubusercontent.com/37951309/42367958-f7954240-812f-11e8-981c-b635b0acc1a3.JPG)

**Comment by rijal10** [comment]
the image is for me just for example to you! and so I took it on a small scale. if you agree with my logo you can choose the color you like!

then I will give the file along with the logo formats that you need and do not forget also with the original file!

once again I say this fits perfectly with your application very sweet impression!

**Comment by jamesstar89** [comment]
Lets roll with the blue :)

**Comment by rijal10** [comment]
please sir!
I have provided the appropriate in the following link:
https://drive.google.com/open?id=1fbuXSzaTHAegCaN57EDgtb-MPIh3KSKI

**Comment by rijal10** [comment]
i will help you to update your redme with new logo.

**Comment by jamesstar89** [comment]
Thanks @rijal10 I'll be sure to add it into the readme with a contribution to your username.

Thanks so much :)
