### ISSUE TITLE
Space and <br> to typed texts

### ISSUE THREAD

**Issue by ksidedev** [puffstream/stream-base-product#8]
When a text is added and I add a gap say a new line. When it renders to grid view it removes all spaces.

**Comment by jamesstar89** [comment]
For list view, it does this deliberately and displays it as summary text. You can customise the text in the list page by replacing:

**list.blade.php**
`{{ str_limit($value->post, $limit = 350, $end = '...') }}`

With...

**detail.blade.php**
`$sanitized = htmlspecialchars($value->post, ENT_QUOTES);
echo str_replace(array("\r\n", "\n"), array("<br />", "<br />"), $sanitized);`
